### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by Pyro979** [ezekg/sympm#1]
Don't know if it's related, but i wasn't able to install without using sudo.

But bigger problem is when I try to run it just errors out:

vagrant@vagrant-ubuntu-trusty-64:-$ cd /vagrant/app_ng vagrant@vagrant-ubuntu-trusty-64:/vagrant/app_ng$ sympm install
/usr/lib/node_modules/sympm/index.js:4 
const untildify = require("untildify") 
AAAAA

SyntaxError: Use of const in strict mode. at Module._compile (module.js:439:25) at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12) 
at Function.Module.runMain (module.js:497:10) 
at startup (node.js:119:16)
at node.js:902:3 

node npm versions are:
vagrant@vagrant-ubuntu-trusty-64:/vagrant/app_ng$ node -v 
v0.10.25
vagrant@vagrant-ubuntu-trusty-64:/vagrant/app_ng$ npm -v
3.10.5

I'd love to get this working as part of a vagrant file, but i can't even run it via ssh =c((

**Comment by ezekg** [comment]
You're using an old version of Node that looks like it doesn't support ES6. You'll need to update it. I'd recommend using NVM or something similar to handle installing Node without `sudo`.

**Comment by Pyro979** [comment]
That was it. Explains a few other issues I was having as well.

Side note, I made a few small changes in your script because I run it via vagrant's provisioning. So whenever it was waiting for the input, I just added the correct value to variable. 

Is that something you can add to the script itself? Some sort of silent mode?

**Comment by ezekg** [comment]
Cool. What do you mean? It shouldn't be prompting you for any input. Are you running it with sudo or something?
