### ISSUE TITLE
npm ls shows all(?) dependencies as missing

### ISSUE THREAD

**Issue by andrewc89** [ezekg/sympm#2]
I stumbled on your package because I was having so many issues with npm dependencies in an Ubuntu Vagrant box on a Windows host. Running `npm i` during provisioning was resulting in all different kinds of errors - literally a different error every time. Using sympm fixed all of these problems immediately, so thank you so much for this!

I do have one remaining problem, however - When running `npm ls` it lists seemingly all dependencies as missing. Here is the output concerning a single dependency, `@babel/cli`:
```
├─┬ @babel/cli@7.0.0-beta.42
│ ├── UNMET OPTIONAL DEPENDENCY chokidar@^1.6.1
│ ├── UNMET DEPENDENCY commander@^2.8.1
│ ├── UNMET DEPENDENCY convert-source-map@^1.1.0
│ ├── UNMET DEPENDENCY fs-readdir-recursive@^1.0.0
│ ├─┬ glob@7.1.2
│ │ ├── UNMET DEPENDENCY fs.realpath@^1.0.0
│ │ ├── UNMET DEPENDENCY inflight@^1.0.4
│ │ ├── UNMET DEPENDENCY inherits@2
│ │ ├── UNMET DEPENDENCY minimatch@^3.0.4
│ │ ├── UNMET DEPENDENCY once@^1.3.0
│ │ └── UNMET DEPENDENCY path-is-absolute@^1.0.0
│ ├── UNMET DEPENDENCY lodash@^4.2.0
│ ├─┬ output-file-sync@2.0.1
│ │ ├── UNMET DEPENDENCY graceful-fs@^4.1.11
│ │ ├── UNMET DEPENDENCY is-plain-obj@^1.1.0
│ │ └── UNMET DEPENDENCY mkdirp@^0.5.1
│ ├── UNMET DEPENDENCY slash@^1.0.0
│ └── UNMET DEPENDENCY source-map@^0.5.0

npm ERR! missing: commander@^2.8.1, required by @babel/cli@7.0.0-beta.42
npm ERR! missing: convert-source-map@^1.1.0, required by @babel/cli@7.0.0-beta.42
npm ERR! missing: fs-readdir-recursive@^1.0.0, required by @babel/cli@7.0.0-beta.42
npm ERR! missing: lodash@^4.2.0, required by @babel/cli@7.0.0-beta.42
npm ERR! missing: slash@^1.0.0, required by @babel/cli@7.0.0-beta.42
npm ERR! missing: source-map@^0.5.0, required by @babel/cli@7.0.0-beta.42
npm ERR! missing: fs.realpath@^1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@^1.0.4, required by glob@7.1.2
npm ERR! missing: inherits@2, required by glob@7.1.2
npm ERR! missing: minimatch@^3.0.4, required by glob@7.1.2
npm ERR! missing: once@^1.3.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@^1.0.0, required by glob@7.1.2
npm ERR! missing: graceful-fs@^4.1.11, required by output-file-sync@2.0.1
npm ERR! missing: is-plain-obj@^1.1.0, required by output-file-sync@2.0.1
npm ERR! missing: mkdirp@^0.5.1, required by output-file-sync@2.0.1
```

but of course these packages do exist:

```
$ cat node_modules/commander/package.json | grep version
  "version": "2.15.0"
```

Here is some version info:

node: 8.10.0
npm: 5.6.0

This may just be an issue for npm, but I figured it was safe to start here. I have googled around a bit but the `npm link` functionality makes it difficult to find results for entire node_modules directories that are symlinked and not just individual dependencies.

**Comment by andrewc89** [comment]
Just tried this with the following environment and did *not* have this issue. `npm ls` returned no errors.

node: 6.13.1
npm: 3.10.10

**Comment by ezekg** [comment]
This seems to be an issue with npm v5 not including linked modules under `npm ls`.

**Comment by ezekg** [comment]
I'm going to close this, since it seems to be an issue with npm.
