### ISSUE TITLE
How sympm works?

### ISSUE THREAD

**Issue by aviNrich** [ezekg/sympm#3]
Hi.
"Creates a symlink from ./node_modules to ~/.sympm/<currentDirBasename>/node_modules and runs npm install..."

If symlink is impossible, how can this solution works by adding a symlink?🤔
Thanks

**Comment by ezekg** [comment]
This repo was originally made to work around this issue: https://github.com/npm/npm/issues/7308

I have no idea if that issue still exists since I no longer use npm or Vagrant.
